'use client'

import { useState, useEffect } from 'react'
import { motion } from 'framer-motion'
import { tasksApi } from '@/lib/api'
import toast from 'react-hot-toast'
import { CheckSquare, Plus, Calendar, Clock, User, MoreVertical, Sparkles, ListChecks } from 'lucide-react'

interface Task {
  id: string
  title: string
  description: string
  status: string
  priority: string
  assignee: string
  due_date: string
  lead_id: string
}

export default function TasksView() {
  const [tasks, setTasks] = useState<Task[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [showAddModal, setShowAddModal] = useState(false)
  const [showAiModal, setShowAiModal] = useState(false)
  const [filter, setFilter] = useState('all')

  useEffect(() => {
    loadTasks()
  }, [])

  const loadTasks = async () => {
    try {
      const data = await tasksApi.list()
      setTasks(data.tasks || [])
    } catch (error) {
      toast.error('Failed to load tasks')
    } finally {
      setIsLoading(false)
    }
  }

  const handleAiGenerate = async (note: string) => {
    try {
      const suggestion = await tasksApi.generate(note, {})
      toast.success('Task generated by AI!')
      // Auto-create the task
      await tasksApi.create({
        title: suggestion.suggestion?.title || 'New Task',
        description: suggestion.suggestion?.description || note,
        priority: suggestion.suggestion?.priority || 'medium',
        due_date: new Date(Date.now() + (suggestion.suggestion?.due_date_days || 7) * 86400000).toISOString(),
        tenant_id: 'default',
      })
      loadTasks()
      setShowAiModal(false)
    } catch (error) {
      toast.error('Failed to generate task')
    }
  }

  const handleStatusChange = async (taskId: string, newStatus: string) => {
    try {
      await tasksApi.update(taskId, { status: newStatus })
      toast.success('Task updated')
      loadTasks()
    } catch (error) {
      toast.error('Failed to update task')
    }
  }

  const filteredTasks = tasks.filter(task => {
    if (filter === 'all') return true
    if (filter === 'pending') return task.status !== 'done'
    if (filter === 'completed') return task.status === 'done'
    return true
  })

  const stats = {
    total: tasks.length,
    pending: tasks.filter(t => t.status !== 'done').length,
    completed: tasks.filter(t => t.status === 'done').length,
    urgent: tasks.filter(t => t.priority === 'urgent').length,
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="space-y-6"
    >
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Tasks</h1>
          <p className="text-gray-600">Stay organized and track your progress</p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={() => setShowAiModal(true)}
            className="flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-papabase-purple to-papabase-pink text-white rounded-xl font-medium hover:shadow-lg transition-shadow"
          >
            <Sparkles size={20} />
            AI Generate
          </button>
          <button
            onClick={() => setShowAddModal(true)}
            className="flex items-center gap-2 px-6 py-3 bg-papabase-green text-white rounded-xl font-medium hover:bg-papabase-teal transition-colors"
          >
            <Plus size={20} />
            Add Task
          </button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Total Tasks', value: stats.total, color: 'bg-papabase-purple' },
          { label: 'Pending', value: stats.pending, color: 'bg-yellow-500' },
          { label: 'Completed', value: stats.completed, color: 'bg-papabase-green' },
          { label: 'Urgent', value: stats.urgent, color: 'bg-red-500' },
        ].map((stat) => (
          <div key={stat.label} className="bg-white p-4 rounded-xl shadow-sm">
            <p className="text-2xl font-bold text-gray-800">{stat.value}</p>
            <p className="text-sm text-gray-500">{stat.label}</p>
          </div>
        ))}
      </div>

      {/* Filter Tabs */}
      <div className="flex gap-2">
        {['all', 'pending', 'completed'].map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={`px-4 py-2 rounded-lg font-medium capitalize transition-colors ${
              filter === f
                ? 'bg-papabase-purple text-white'
                : 'bg-white text-gray-600 hover:bg-gray-100'
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Tasks Grid */}
      <div className="grid gap-4">
        {filteredTasks.length === 0 ? (
          <div className="bg-white p-12 rounded-xl text-center">
            <CheckSquare size={48} className="mx-auto mb-4 text-gray-300" />
            <p className="text-gray-500">No tasks yet. Create one to get started!</p>
          </div>
        ) : (
          filteredTasks.map((task) => (
            <div
              key={task.id}
              className={`bg-white p-4 rounded-xl shadow-sm border-l-4 ${
                task.priority === 'urgent' ? 'border-red-500' :
                task.priority === 'high' ? 'border-yellow-500' :
                'border-papabase-teal'
              }`}
            >
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => handleStatusChange(task.id, task.status === 'done' ? 'todo' : 'done')}
                      className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors ${
                        task.status === 'done'
                          ? 'bg-papabase-green border-papabase-green text-white'
                          : 'border-gray-300 hover:border-papabase-teal'
                      }`}
                    >
                      {task.status === 'done' && <CheckSquare size={14} />}
                    </button>
                    <h3 className={`font-medium ${
                      task.status === 'done' ? 'text-gray-400 line-through' : 'text-gray-800'
                    }`}>
                      {task.title}
                    </h3>
                  </div>
                  {task.description && (
                    <p className="text-gray-600 mt-2 ml-9">{task.description}</p>
                  )}
                  <div className="flex items-center gap-4 mt-3 ml-9 text-sm text-gray-500">
                    <span className="flex items-center gap-1">
                      <Clock size={14} />
                      {task.priority}
                    </span>
                    <span className="flex items-center gap-1">
                      <Calendar size={14} />
                      {new Date(task.due_date).toLocaleDateString()}
                    </span>
                    {task.assignee && (
                      <span className="flex items-center gap-1">
                        <User size={14} />
                        {task.assignee}
                      </span>
                    )}
                  </div>
                </div>
                <button className="p-2 text-gray-400 hover:bg-gray-100 rounded-lg">
                  <MoreVertical size={18} />
                </button>
              </div>
            </div>
          ))
        )}
      </div>

      {/* Add Task Modal */}
      {showAddModal && (
        <AddTaskModal
          onClose={() => setShowAddModal(false)}
          onAdd={async (data) => {
            try {
              await tasksApi.create(data)
              toast.success('Task created!')
              loadTasks()
              setShowAddModal(false)
            } catch (error) {
              toast.error('Failed to create task')
            }
          }}
        />
      )}

      {/* AI Generate Modal */}
      {showAiModal && (
        <AiGenerateModal
          onClose={() => setShowAiModal(false)}
          onGenerate={handleAiGenerate}
        />
      )}
    </motion.div>
  )
}

function AddTaskModal({ onClose, onAdd }: { onClose: () => void, onAdd: (data: any) => Promise<void> }) {
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    priority: 'medium',
    due_date: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    assignee: '',
    tenant_id: 'default',
  })

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl p-6 max-w-md w-full">
        <h3 className="text-xl font-bold text-gray-800 mb-4">Add New Task</h3>
        <form onSubmit={(e) => { e.preventDefault(); onAdd(formData); }} className="space-y-4">
          <input
            type="text"
            placeholder="Task title *"
            value={formData.title}
            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-green"
            required
          />
          <textarea
            placeholder="Description"
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-green"
            rows={3}
          />
          <select
            value={formData.priority}
            onChange={(e) => setFormData({ ...formData, priority: e.target.value })}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-green"
          >
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
            <option value="urgent">Urgent</option>
          </select>
          <input
            type="date"
            value={formData.due_date}
            onChange={(e) => setFormData({ ...formData, due_date: e.target.value })}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-green"
          />
          <input
            type="text"
            placeholder="Assignee"
            value={formData.assignee}
            onChange={(e) => setFormData({ ...formData, assignee: e.target.value })}
            className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-green"
          />
          <div className="flex gap-3 pt-4">
            <button type="button" onClick={onClose} className="flex-1 py-3 border border-gray-200 rounded-xl font-medium hover:bg-gray-50">
              Cancel
            </button>
            <button type="submit" className="flex-1 py-3 bg-papabase-green text-white rounded-xl font-medium hover:bg-papabase-teal">
              Create Task
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}

function AiGenerateModal({ onClose, onGenerate }: { onClose: () => void, onGenerate: (note: string) => Promise<void> }) {
  const [note, setNote] = useState('')

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl p-6 max-w-md w-full">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="text-papabase-purple" size={24} />
          <h3 className="text-xl font-bold text-gray-800">AI Task Generator</h3>
        </div>
        <p className="text-gray-600 mb-4">
          Describe what you need to do in plain language, and AI will create a structured task for you.
        </p>
        <textarea
          placeholder="e.g., 'Follow up with John about the roofing project proposal'"
          value={note}
          onChange={(e) => setNote(e.target.value)}
          className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:border-papabase-purple"
          rows={4}
          autoFocus
        />
        <div className="flex gap-3 mt-4">
          <button type="button" onClick={onClose} className="flex-1 py-3 border border-gray-200 rounded-xl font-medium hover:bg-gray-50">
            Cancel
          </button>
          <button
            type="submit"
            onClick={() => onGenerate(note)}
            disabled={!note.trim()}
            className="flex-1 py-3 bg-gradient-to-r from-papabase-purple to-papabase-pink text-white rounded-xl font-medium hover:shadow-lg disabled:opacity-50"
          >
            Generate Task
          </button>
        </div>
      </div>
    </div>
  )
}
